version: "2.3"

services:
  jupyter:
    container_name: tensorflow-jupyter-notebooks
    image: tensorflow/tensorflow:nightly-gpu
    ports:
      - 8888:8888
    entrypoint:
      - /notebooks/workdir/entrypoint.sh
    volumes:
      - ./:/notebooks/workdir
    restart: unless-stopped

  ncsdk:
    container_name: ncsdk-bash
    image: heliconwave/ncsdk:v2
    environment: 
      - LOCAL_USER_ID=${LOCAL_USER_ID}
      - MODELS_ROOT=/home/docker/models
      - DISPLAY=unix${DISPLAY}
      - TERM=xterm-256color
      - QT_X11_NO_MITSHM=1
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:ro
      - ./:/home/docker/workspace
      - /dev:/dev
    privileged: true
    stdin_open: true
    tty: true
    network_mode: "host"

  object-detection:
    container_name: object-detection-bash
    image: heliconwave/object-detection:v3
    runtime: nvidia
    stdin_open: true
    tty: true
    ports:
      - 8888:8888
      - 0.0.0.0:6006:6006
    environment: 
      - LOCAL_USER_ID=${LOCAL_USER_ID}
      - MODELS_ROOT=/tmp/models
      - DISPLAY=unix${DISPLAY}
      - TERM=xterm-256color
    privileged: true
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:ro
      - ./:/tmp
      - /dev/video0:/dev/video0
